### ISSUE TITLE
NG_APP_ANGULAR_APP_BUTTER_CMS environment variable prefix is long?

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/angular-starter-buttercms#2]
Just checking, as I know some frameworks require certain prefixes for environment variables, while others are more flexible - is the NG_APP_ANGULAR_APP_ prefix section required for environment variables? If not, is it possible to shorten to either NG_ANGULAR_APP or even NG_ANGULAR_ (so that the token variable looks something like NG_ANGULAR_BUTTER_CMS_API_KEY and the preview variable looks something like NG_ANGULAR_BUTTER_CMS_PREVIEW?

**Comment by pikorkar** [comment]
The prefix section if NG_APP, so I shortened the variables to
NG_APP_ANGULAR_BUTTER_CMS_API_KEY, NG_APP_ANGULAR_BUTTER_CMS_PREVIEW.

**Comment by ViolanteCodes** [comment]
@pikorkar Thank you. In the future, can you open PR's for changes, as opposed to committing directly to repo? Thanks!
