### ISSUE TITLE
Necessary domain is already taken in vercel

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/angular-starter-buttercms#3]
Can you delete your vercel app that is at angular-starter-buttercms.vercel.app? We'd like to use that domain name, but it's already currently taken?

**Comment by prokopsimek** [comment]
@ViolanteCodes Hi Marie, I'm sorry, I accidentally took the domain to Vercel. I just deleted the project there. Can you please try again? cc @pikorkar
